# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Adept'), (2, 'Advanced'), (3, 'Expert')], default=0),
            preserve_default=False,
        ),
    ]
