# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_project_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
